[versions]
#Plugins
detekt = "2.0.0-alpha.1"
kotlin = "2.2.21"
kover = "0.9.3"
ktlint = "14.0.1"
ktlint-cli = "1.8.0"
shadow = "9.3.0"
versions-plugin = "0.53.0"

# Libs
classgraph = "4.8.184"
hoplite = "2.9.0"
jackson = "3.0.3"
koin = "4.1.1"
kotest = "6.0.7"
kotlin-coroutines = "1.10.2"
ktor = "3.3.2"
log4j = "2.25.3"
logback = "1.5.22"
mockk = "1.14.6"
okhttp = "5.3.1"
yauaa = "7.32.0"

[libraries]
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
hoplite-core = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
hoplite-yaml = { module = "com.sksamuel.hoplite:hoplite-yaml", version.ref = "hoplite" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson"}
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-logger = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
kotlin-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlin-coroutines" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
log4j-to-slf4j = { module = "org.apache.logging.log4j:log4j-to-slf4j", version.ref = "log4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
yauaa = { module = "nl.basjes.parse.useragent:yauaa", version.ref = "yauaa" }

# Tests
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
kotest-extensions-koin = { module = "io.kotest:kotest-extensions-koin", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
